

# mybatisplus ��־����
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # logic-delete-field: flag # ȫ���߼�ɾ����ʵ���ֶ���(since 3.3.0,���ú���Ժ��Բ����ò���2)
      logic-delete-value: 1 # �߼���ɾ��ֵ(Ĭ��Ϊ 1)
      logic-not-delete-value: 0 # �߼�δɾ��ֵ(Ĭ��Ϊ 0)
      db-type: mysql
  mapper-locations: mapper/*.xml
  type-aliases-package: com.roily.entity
  type-handlers-package: com.roily.typeHandler
  type-enums-package: com.roily.enums
#      table-prefix: u
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&charactEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    password: 123456
    username: root